from __future__ import annotations

from typing import Any


def _entry(
    *,
    key: str,
    scope_allowed: list[str],
    value_type: str,
    category: str,
    subcategory: str,
    description: str,
    default_value_json: Any = None,
    validation_json: dict[str, Any] | None = None,
    is_sensitive: bool = False,
    is_developer_only: bool = False,
    requires_restart: bool = False,
    requires_reprice: bool = False,
    requires_recalc: bool = False,
    min_role_to_view: str | None = None,
    min_role_to_edit: str | None = None,
) -> dict[str, Any]:
    return {
        "key": key,
        "scope_allowed": scope_allowed,
        "type": value_type,
        "default_value_json": default_value_json,
        "validation_json": validation_json or {},
        "description": description,
        "category": category,
        "subcategory": subcategory,
        "is_sensitive": is_sensitive,
        "is_developer_only": is_developer_only,
        "requires_restart": requires_restart,
        "requires_reprice": requires_reprice,
        "requires_recalc": requires_recalc,
        "min_role_to_view": min_role_to_view,
        "min_role_to_edit": min_role_to_edit,
    }


def _org(
    key: str,
    value_type: str,
    subcategory: str,
    description: str,
    default: Any = None,
    validation: dict[str, Any] | None = None,
    *,
    is_sensitive: bool = False,
    requires_restart: bool = False,
    requires_reprice: bool = False,
    requires_recalc: bool = False,
) -> dict[str, Any]:
    return _entry(
        key=key,
        scope_allowed=["ORG"],
        value_type=value_type,
        category="organization",
        subcategory=subcategory,
        description=description,
        default_value_json=default,
        validation_json=validation,
        is_sensitive=is_sensitive,
        requires_restart=requires_restart,
        requires_reprice=requires_reprice,
        requires_recalc=requires_recalc,
        min_role_to_view="manager",
        min_role_to_edit="admin",
    )


def _store(
    key: str,
    value_type: str,
    subcategory: str,
    description: str,
    default: Any = None,
    validation: dict[str, Any] | None = None,
    *,
    min_role_to_edit: str = "manager",
    requires_restart: bool = False,
    requires_reprice: bool = False,
    requires_recalc: bool = False,
) -> dict[str, Any]:
    return _entry(
        key=key,
        scope_allowed=["STORE"],
        value_type=value_type,
        category="store",
        subcategory=subcategory,
        description=description,
        default_value_json=default,
        validation_json=validation,
        requires_restart=requires_restart,
        requires_reprice=requires_reprice,
        requires_recalc=requires_recalc,
        min_role_to_view="cashier",
        min_role_to_edit=min_role_to_edit,
    )


def _device(
    key: str,
    value_type: str,
    subcategory: str,
    description: str,
    default: Any = None,
    validation: dict[str, Any] | None = None,
    *,
    requires_restart: bool = False,
) -> dict[str, Any]:
    return _entry(
        key=key,
        scope_allowed=["DEVICE"],
        value_type=value_type,
        category="device",
        subcategory=subcategory,
        description=description,
        default_value_json=default,
        validation_json=validation,
        requires_restart=requires_restart,
        min_role_to_view="cashier",
        min_role_to_edit="manager",
    )


def _user(
    key: str,
    value_type: str,
    subcategory: str,
    description: str,
    default: Any = None,
    validation: dict[str, Any] | None = None,
    *,
    min_role_to_edit: str = "cashier",
) -> dict[str, Any]:
    return _entry(
        key=key,
        scope_allowed=["USER"],
        value_type=value_type,
        category="user",
        subcategory=subcategory,
        description=description,
        default_value_json=default,
        validation_json=validation,
        min_role_to_view="cashier",
        min_role_to_edit=min_role_to_edit,
    )


SETTINGS_CATALOG: list[dict[str, Any]] = [
    # A1) Identity & branding
    _org("org.brand.name", "string", "identity_branding", "Display brand name."),
    _org("org.brand.legal_name", "string", "identity_branding", "Legal entity name."),
    _org("org.brand.logo_light_url", "string", "identity_branding", "Light theme logo URL."),
    _org("org.brand.logo_dark_url", "string", "identity_branding", "Dark theme logo URL."),
    _org("org.brand.favicon_url", "string", "identity_branding", "Favicon URL."),
    _org("org.brand.primary_color", "color", "identity_branding", "Primary brand color."),
    _org("org.brand.accent_color", "color", "identity_branding", "Accent brand color."),
    _org("org.brand.background_style", "enum", "identity_branding", "Background style preset.", "default", {"enum": ["default", "subtle_pattern", "gradient"]}),
    _org("org.brand.receipt_header_text", "string", "identity_branding", "Receipt header text."),
    _org("org.brand.receipt_footer_text", "string", "identity_branding", "Receipt footer text."),
    _org("org.brand.support_email", "string", "identity_branding", "Support email address."),
    _org("org.brand.support_phone", "string", "identity_branding", "Support phone number."),
    _org("org.brand.website_url", "string", "identity_branding", "Public website URL."),
    # A2) UI / experience defaults
    _org("org.ui.default_language", "string", "ui_defaults", "Default language code.", "en-US"),
    _org("org.ui.default_currency", "string", "ui_defaults", "Default currency code.", "USD"),
    _org("org.ui.date_format", "string", "ui_defaults", "Date format.", "YYYY-MM-DD"),
    _org("org.ui.time_format_12h", "bool", "ui_defaults", "Use 12-hour clock.", True),
    _org("org.ui.number_format_locale", "string", "ui_defaults", "Locale for number formatting.", "en-US"),
    _org("org.ui.accessibility.text_scale_default", "decimal", "ui_defaults", "Default text scale.", 1.0, {"min": 0.8, "max": 1.6}),
    _org("org.ui.sound_enabled_default", "bool", "ui_defaults", "Enable sound by default.", True),
    _org("org.ui.haptics_enabled_default", "bool", "ui_defaults", "Enable haptics by default.", False),
    # A3) Permissions model defaults
    _org("org.auth.roles_enabled", "bool", "auth", "Enable role-based permission model.", True),
    _org("org.auth.user_permission_overrides_enabled", "bool", "auth", "Enable per-user overrides.", True),
    _org("org.auth.require_2fa_for_admin", "bool", "auth", "Require 2FA for admin users.", False),
    _org("org.auth.password_policy_json", "json", "auth", "Password policy configuration.", {"min_length": 12, "require_complexity": True, "expiry_days": 0}),
    _org("org.auth.pin_policy_json", "json", "auth", "PIN policy configuration.", {"length": 6, "max_retries": 5, "lockout_seconds": 300}),
    _org("org.auth.session_timeout_seconds_default", "duration_seconds", "auth", "Default session timeout in seconds.", 28800),
    _org("org.auth.require_manager_override_for_actions", "json", "auth", "Action list requiring manager override.", []),
    # A4) Tax & compliance defaults
    _org("org.tax.default_tax_region_id", "string", "tax_compliance", "Default tax region identifier."),
    _org("org.tax.prices_include_tax_default", "bool", "tax_compliance", "Whether prices include tax by default.", False, requires_reprice=True),
    _org("org.tax.rounding_mode", "enum", "tax_compliance", "Tax rounding mode.", "half_up", {"enum": ["bankers", "half_up", "half_down", "up", "down"]}, requires_recalc=True),
    _org("org.compliance.receipt_requirements_json", "json", "tax_compliance", "Receipt compliance requirements.", {}),
    _org("org.compliance.age_restriction_enabled", "bool", "tax_compliance", "Enable age restrictions.", False),
    _org("org.compliance.age_restriction_min_age", "int", "tax_compliance", "Minimum age when age restriction is enabled.", 21, {"min": 0, "max": 120}),
    _org("org.compliance.audit_retention_days", "int", "tax_compliance", "Audit retention period in days.", 3650, {"min": 30}),
    # A5) Payments
    _org("org.payments.enabled_methods", "json", "payments", "Enabled payment methods.", ["CASH", "CARD"]),
    _org("org.payments.allow_split_tender", "bool", "payments", "Allow split tender.", True),
    _org("org.payments.allow_tips", "bool", "payments", "Allow tips.", False),
    _org("org.payments.tip_suggestions_bps_list", "json", "payments", "Tip suggestion list in basis points.", [1500, 1800, 2000]),
    _org("org.payments.require_signature_threshold_cents", "decimal_cents", "payments", "Signature threshold in cents.", 0),
    _org("org.payments.cash_rounding_enabled", "bool", "payments", "Enable cash rounding.", False),
    _org("org.payments.cash_drawer_required_for_cash", "bool", "payments", "Require drawer for cash tenders.", True),
    _org("org.payments.offline_mode_enabled", "bool", "payments", "Enable payments offline mode.", False),
    _org("org.payments.offline_max_amount_cents", "decimal_cents", "payments", "Max offline amount in cents.", 0),
    _org("org.payments.refunds_require_manager", "bool", "payments", "Require manager for refunds.", True),
    _org("org.payments.voids_require_manager", "bool", "payments", "Require manager for voids.", True),
    _org("org.payments.processor.public_config_json", "json", "payments", "Public processor configuration.", {}),
    _org("org.payments.processor.secret_refs", "json", "payments", "Secret reference identifiers.", {}, is_sensitive=True),
    # A6) Pricing & discounts policy
    _org("org.pricing.allow_discounts", "bool", "pricing", "Allow discounts.", True, requires_reprice=True),
    _org("org.pricing.discount_reason_required", "bool", "pricing", "Require discount reason.", True),
    _org("org.pricing.max_discount_bps_without_manager", "int", "pricing", "Max discount without manager (bps).", 1000, {"min": 0, "max": 10000}),
    _org("org.pricing.allow_price_overrides", "bool", "pricing", "Allow price overrides.", True, requires_reprice=True),
    _org("org.pricing.price_override_reason_required", "bool", "pricing", "Require price override reason.", True),
    _org("org.pricing.price_override_limit_bps_without_manager", "int", "pricing", "Price override cap without manager (bps).", 500, {"min": 0, "max": 10000}),
    _org("org.pricing.coupons_enabled", "bool", "pricing", "Enable coupons.", True, requires_reprice=True),
    _org("org.pricing.stack_discounts_allowed", "bool", "pricing", "Allow stacked discounts.", False, requires_reprice=True),
    _org("org.pricing.promotions_engine_enabled", "bool", "pricing", "Enable promotions engine.", True, requires_reprice=True),
    _org("org.pricing.default_price_book_id", "string", "pricing", "Default price book reference.", None, requires_reprice=True),
    # A7) Returns / exchanges policy
    _org("org.returns.enabled", "bool", "returns", "Enable returns flow.", True),
    _org("org.returns.require_receipt", "bool", "returns", "Require receipt for returns.", True),
    _org("org.returns.return_window_days", "int", "returns", "Return window in days.", 30, {"min": 0}),
    _org("org.returns.allow_no_receipt_returns", "bool", "returns", "Allow no-receipt returns.", False),
    _org("org.returns.no_receipt_return_limit_cents", "decimal_cents", "returns", "No-receipt return cap in cents.", 0),
    _org("org.returns.returns_to_original_tender_default", "bool", "returns", "Return to original tender by default.", True),
    _org("org.returns.restock_fee_bps", "int", "returns", "Restock fee in basis points.", 0, {"min": 0, "max": 10000}),
    _org("org.returns.require_manager_over_threshold_cents", "decimal_cents", "returns", "Manager approval threshold for returns.", 0),
    # A8) Inventory & purchasing defaults
    _org("org.inventory.costing_method", "enum", "inventory", "Inventory costing method.", "WAC", {"enum": ["WAC", "FIFO"]}),
    _org("org.inventory.allow_negative_inventory", "bool", "inventory", "Allow negative inventory.", False),
    _org("org.inventory.low_stock_threshold_default", "int", "inventory", "Default low stock threshold.", 5, {"min": 0}),
    _org("org.inventory.reorder_suggestions_enabled", "bool", "inventory", "Enable reorder suggestions.", True),
    _org("org.inventory.receive_requires_vendor", "bool", "inventory", "Require vendor on receives.", True),
    _org("org.inventory.barcode_ambiguity_policy", "enum", "inventory", "Policy for ambiguous barcode matches.", "hard_stop", {"enum": ["hard_stop", "pick_first", "prompt"]}),
    _org("org.inventory.identifier_lookup_priority_json", "json", "inventory", "Identifier lookup order.", ["UPC", "ALT_BARCODE", "VENDOR_CODE"]),
    _org("org.inventory.counts.require_reason_codes", "bool", "inventory", "Require reason codes for counts.", True),
    _org("org.inventory.transfers_enabled", "bool", "inventory", "Enable store transfers.", True),
    _org("org.inventory.adjustments_require_manager", "bool", "inventory", "Require manager for adjustments.", True),
    # A9) Vendors
    _org("org.vendors.enabled", "bool", "vendors", "Enable vendor features.", True),
    _org("org.vendors.require_terms", "bool", "vendors", "Require vendor terms.", False),
    _org("org.vendors.default_payment_terms", "string", "vendors", "Default vendor payment terms.", "NET30"),
    _org("org.vendors.allow_vendor_specific_skus", "bool", "vendors", "Allow vendor-specific SKUs.", True),
    _org("org.vendors.vendor_product_implicit_relation", "bool", "vendors", "Vendor-product relationship is implicit.", True),
    # A10) Loyalty program (org)
    _org("org.loyalty.enabled", "bool", "loyalty", "Enable loyalty program.", False),
    _org("org.loyalty.program_name", "string", "loyalty", "Loyalty program display name.", "Rewards"),
    _org("org.loyalty.earn_rate_points_per_cent", "decimal", "loyalty", "Points earned per cent spent.", 0.0),
    _org("org.loyalty.redeem_rate_cents_per_point", "decimal", "loyalty", "Cents per point when redeeming.", 0.0),
    _org("org.loyalty.points_expire_enabled", "bool", "loyalty", "Enable points expiration.", False),
    _org("org.loyalty.points_expire_days", "int", "loyalty", "Points expiration days.", 365, {"min": 1}),
    _org("org.loyalty.enrollment_required_fields_json", "json", "loyalty", "Required enrollment fields.", ["first_name", "phone"]),
    _org("org.loyalty.allow_manual_adjustments", "bool", "loyalty", "Allow manual points adjustments.", False),
    _org("org.loyalty.rounding_rule", "enum", "loyalty", "Loyalty points rounding rule.", "floor", {"enum": ["floor", "round", "ceil"]}),
    # A11) Receipts / printing
    _org("org.receipts.enabled", "bool", "receipts", "Enable receipts.", True),
    _org("org.receipts.default_delivery", "enum", "receipts", "Default receipt delivery mode.", "print", {"enum": ["print", "email", "sms", "none"]}),
    _org("org.receipts.require_customer_for_digital", "bool", "receipts", "Require customer for digital receipts.", True),
    _org("org.receipts.paper_size", "enum", "receipts", "Paper size for printed receipts.", "80mm", {"enum": ["58mm", "80mm", "A4", "letter"]}),
    _org("org.receipts.show_tax_breakdown", "bool", "receipts", "Show tax breakdown on receipts.", True),
    _org("org.receipts.show_savings", "bool", "receipts", "Show savings on receipts.", True),
    _org("org.receipts.show_cashier_name", "bool", "receipts", "Show cashier name on receipts.", True),
    # A12) Notifications & tasks
    _org("org.notifications.enabled", "bool", "notifications_tasks", "Enable notifications.", True),
    _org("org.notifications.email_enabled", "bool", "notifications_tasks", "Enable email notifications.", True),
    _org("org.notifications.sms_enabled", "bool", "notifications_tasks", "Enable SMS notifications.", False),
    _org("org.tasks.enabled", "bool", "notifications_tasks", "Enable tasks module.", True),
    _org("org.tasks.require_ack", "bool", "notifications_tasks", "Require acknowledgements for tasks.", False),
    _org("org.tasks.reminders_enabled", "bool", "notifications_tasks", "Enable task reminders.", True),
    # A13) Reporting & analytics
    _org("org.analytics.enabled", "bool", "analytics", "Enable analytics.", True),
    _org("org.analytics.data_retention_days", "int", "analytics", "Analytics retention days.", 1095, {"min": 30}),
    _org("org.analytics.default_dashboard_layout_json", "json", "analytics", "Default analytics dashboard layout.", {}),
    _org("org.analytics.allow_export_csv", "bool", "analytics", "Allow CSV exports.", True),
    _org("org.analytics.anomaly_detection_enabled", "bool", "analytics", "Enable anomaly detection.", False),
    _org("org.analytics.outlier_thresholds_json", "json", "analytics", "Outlier detection thresholds.", {}),
    # A14) Security hardening
    _org("org.security.ip_allowlist_enabled", "bool", "security", "Enable IP allowlist.", False),
    _org("org.security.ip_allowlist_json", "json", "security", "IP allowlist values.", []),
    _org("org.security.device_enrollment_required", "bool", "security", "Require device enrollment.", False),
    _org("org.security.face_login_enabled", "bool", "security", "Enable face login.", False),
    _org("org.security.face_login_required_for_actions_json", "json", "security", "Actions requiring face login.", []),
    _org("org.security.audit_log_enabled", "bool", "security", "Enable security audit log.", True),
    _org("org.security.session_concurrency_limit", "int", "security", "Max concurrent sessions per user.", 5, {"min": 1}),

    # B1) Store identity / local branding
    _store("store.brand.name", "string", "identity_branding", "Store-level brand name."),
    _store("store.brand.logo_url", "string", "identity_branding", "Store logo URL."),
    _store("store.brand.primary_color", "color", "identity_branding", "Store primary color."),
    _store("store.brand.receipt_header_text", "string", "identity_branding", "Store receipt header."),
    _store("store.brand.receipt_footer_text", "string", "identity_branding", "Store receipt footer."),
    _store("store.brand.support_phone", "string", "identity_branding", "Store support phone."),
    _store("store.brand.support_email", "string", "identity_branding", "Store support email."),
    # B2) Store info
    _store("store.info.address_json", "json", "store_information", "Store address payload.", {}),
    _store("store.info.phone", "string", "store_information", "Store phone number."),
    _store("store.info.manager_contact", "string", "store_information", "Store manager contact."),
    _store("store.info.open_hours_json", "json", "store_information", "Store open hours.", {}),
    # B3) Store timezone / locale
    _store("store.timezone", "string", "timezone_locale", "Store timezone.", "UTC", min_role_to_edit="admin", requires_restart=True),
    _store("store.locale", "string", "timezone_locale", "Store locale.", "en-US", min_role_to_edit="admin", requires_restart=True),
    # B4) Store tax configuration
    _store("store.tax.tax_region_id", "string", "tax", "Store tax region.", min_role_to_edit="admin", requires_recalc=True),
    _store("store.tax.override_rates_json", "json", "tax", "Store tax override rates.", {}, min_role_to_edit="admin", requires_recalc=True),
    _store("store.tax.prices_include_tax", "bool", "tax", "Store-level prices include tax.", False, min_role_to_edit="admin", requires_reprice=True),
    # B5) Payments store rules
    _store("store.payments.enabled_methods_override", "json", "payments", "Store-level enabled payment methods.", []),
    _store("store.payments.cash_drawer_required", "bool", "payments", "Require cash drawer for cash payments.", True),
    _store("store.payments.max_cash_refund_cents_without_admin", "decimal_cents", "payments", "Max cash refund without admin.", 0),
    _store("store.payments.allow_offline_mode", "bool", "payments", "Allow offline mode at store.", False),
    _store("store.payments.offline_limit_cents", "decimal_cents", "payments", "Offline payment limit in cents.", 0),
    # B6) Pricing / promos
    _store("store.pricing.price_book_id_override", "string", "pricing_promos", "Store price book override.", None, requires_reprice=True),
    _store("store.pricing.allow_discounts_override", "bool", "pricing_promos", "Store discount policy override.", True, requires_reprice=True),
    _store("store.pricing.promo_calendar_json", "json", "pricing_promos", "Store promo calendar.", {}, requires_reprice=True),
    _store("store.pricing.happy_hour_rules_json", "json", "pricing_promos", "Store happy hour rules.", {}, requires_reprice=True),
    # B7) Returns policy store overrides
    _store("store.returns.return_window_days_override", "int", "returns", "Store return window override.", 30, {"min": 0}),
    _store("store.returns.allow_no_receipt_override", "bool", "returns", "Store no-receipt return override.", False),
    _store("store.returns.no_receipt_limit_cents_override", "decimal_cents", "returns", "Store no-receipt return cap override.", 0),
    # B8) Inventory rules
    _store("store.inventory.low_stock_threshold_override", "int", "inventory", "Store low stock threshold override.", 5, {"min": 0}),
    _store("store.inventory.allow_negative_inventory_override", "bool", "inventory", "Store negative inventory policy override.", False),
    _store("store.inventory.default_receive_location", "string", "inventory", "Store default receive location."),
    _store("store.inventory.count_schedule_json", "json", "inventory", "Store count schedule.", {}),
    _store("store.inventory.transfer_rules_json", "json", "inventory", "Store transfer rules.", {}),
    # B9) Labor settings (store)
    _store("store.labor.overtime_rules_json", "json", "labor", "Store overtime rules.", {}),
    _store("store.labor.break_rules_json", "json", "labor", "Store break rules.", {}),
    _store("store.labor.time_rounding_minutes", "int", "labor", "Time rounding in minutes.", 0, {"min": 0, "max": 60}),
    _store("store.labor.require_clock_out", "bool", "labor", "Require clock out before session close.", True),
    _store("store.labor.require_manager_approval_edits", "bool", "labor", "Require manager approval for time edits.", True),
    # B10) Operational workflow toggles
    _store("store.ops.enable_customer_display", "bool", "operations", "Enable customer display.", False),
    _store("store.ops.enable_kitchen_display", "bool", "operations", "Enable kitchen display.", False),
    _store("store.ops.require_shift_open_to_sell", "bool", "operations", "Require open shift to sell.", True),
    _store("store.ops.require_register_selection", "bool", "operations", "Require register selection.", True),
    _store("store.ops.cash_management_enabled", "bool", "operations", "Enable cash management workflows.", True),

    # C1) Session & security
    _device("device.session.auto_logout_seconds", "duration_seconds", "session_security", "Auto logout timeout in seconds.", 0, {"min": 0}, requires_restart=True),
    _device("device.session.lock_screen_enabled", "bool", "session_security", "Enable lock screen.", False),
    _device("device.session.lock_screen_pin_required", "bool", "session_security", "Require PIN to unlock lock screen.", False),
    _device("device.session.max_failed_pin_attempts", "int", "session_security", "Max failed PIN attempts.", 5, {"min": 1}),
    _device("device.session.lockout_seconds", "duration_seconds", "session_security", "Lockout duration in seconds.", 60, {"min": 0}),
    # C2) Scan / input behavior
    _device("device.scan.always_listening", "bool", "scan_input", "Scanner always listening mode.", True),
    _device("device.scan.prefix_suffix_handling_json", "json", "scan_input", "Scanner prefix/suffix handling configuration.", {}),
    _device("device.scan.sound_on_scan", "bool", "scan_input", "Play sound on scan.", True),
    _device("device.scan.vibrate_on_scan", "bool", "scan_input", "Vibrate on scan.", False),
    _device("device.scan.debounce_ms", "int", "scan_input", "Scan debounce milliseconds.", 100, {"min": 0}),
    _device("device.scan.unknown_barcode_behavior", "enum", "scan_input", "Behavior for unknown barcodes.", "prompt", {"enum": ["search", "create", "prompt"]}),
    # C3) Register UI behavior
    _device("device.register.big_touch_targets", "bool", "register_ui", "Use larger touch targets.", True),
    _device("device.register.item_row_as_button", "bool", "register_ui", "Treat cart rows as action buttons.", False),
    _device("device.register.drag_drop_enabled", "bool", "register_ui", "Enable drag/drop controls.", True),
    _device("device.register.show_time_top_left", "bool", "register_ui", "Show time in top left.", True),
    _device("device.register.show_manager_badges", "bool", "register_ui", "Show manager badges.", False),
    _device("device.register.cart_behavior_json", "json", "register_ui", "Cart behavior configuration.", {}),
    # C4) Peripherals
    _device("device.peripherals.printer_enabled", "bool", "peripherals", "Printer enabled.", True, requires_restart=True),
    _device("device.peripherals.printer_type", "enum", "peripherals", "Printer type.", "RECEIPT", {"enum": ["RECEIPT", "KITCHEN", "LABEL", "REPORT"]}, requires_restart=True),
    _device("device.peripherals.printer_address", "string", "peripherals", "Printer network/device address.", None, requires_restart=True),
    _device("device.peripherals.cash_drawer_enabled", "bool", "peripherals", "Cash drawer enabled.", True, requires_restart=True),
    _device("device.peripherals.scale_enabled", "bool", "peripherals", "Scale enabled.", False, requires_restart=True),
    _device("device.peripherals.customer_display_enabled", "bool", "peripherals", "Customer display enabled.", False, requires_restart=True),
    _device("device.peripherals.kds_enabled", "bool", "peripherals", "Kitchen display enabled.", False, requires_restart=True),
    # C5) Performance / offline
    _device("device.offline.enabled", "bool", "performance_offline", "Device offline mode enabled.", False),
    _device("device.offline.queue_limit", "int", "performance_offline", "Offline queue max items.", 1000, {"min": 0}),
    _device("device.offline.sync_interval_seconds", "duration_seconds", "performance_offline", "Offline sync interval seconds.", 60, {"min": 1}),
    _device("device.cache.product_cache_ttl_seconds", "duration_seconds", "performance_offline", "Product cache TTL seconds.", 300, {"min": 0}),
    # C6) Appearance (device-level)
    _device("device.ui.theme_mode", "enum", "appearance", "Device theme mode.", "system", {"enum": ["system", "light", "dark"]}),
    _device("device.ui.font_scale", "decimal", "appearance", "Device font scale.", 1.0, {"min": 0.8, "max": 1.6}),
    _device("device.ui.reduce_motion", "bool", "appearance", "Reduce motion on device.", False),

    # D1) Register personalization
    _user("user.register.quick_buttons_layout_json", "json", "register_personalization", "User quick button layout.", {}),
    _user("user.register.favorite_items_json", "json", "register_personalization", "User favorite items.", []),
    _user("user.register.default_discount_reason", "string", "register_personalization", "Default discount reason."),
    _user("user.register.default_payment_method", "string", "register_personalization", "Default payment method.", "CASH"),
    _user("user.register.confirmations_json", "json", "register_personalization", "Confirmation toggles.", {}),
    # D2) Navigation / dashboards
    _user("user.ui.home_dashboard_layout_json", "json", "navigation_dashboards", "Home dashboard layout.", {}),
    _user("user.ui.analytics_layout_json", "json", "navigation_dashboards", "Analytics layout.", {}),
    _user("user.ui.nav_order_json", "json", "navigation_dashboards", "Navigation order.", []),
    _user("user.ui.default_workspace", "enum", "navigation_dashboards", "Default workspace.", "sales", {"enum": ["sales", "inventory", "ops"]}),
    # D3) Notifications
    _user("user.notifications.email_enabled", "bool", "notifications", "Enable user email notifications.", True),
    _user("user.notifications.sms_enabled", "bool", "notifications", "Enable user SMS notifications.", False),
    _user("user.notifications.push_enabled", "bool", "notifications", "Enable user push notifications.", True),
    _user("user.notifications.shift_reminders_enabled", "bool", "notifications", "Enable shift reminders.", True),
    _user("user.notifications.task_reminders_enabled", "bool", "notifications", "Enable task reminders.", True),
    # D4) Accessibility
    _user("user.accessibility.font_scale", "decimal", "accessibility", "Accessibility font scale.", 1.0, {"min": 0.8, "max": 1.8}),
    _user("user.accessibility.high_contrast", "bool", "accessibility", "Enable high contrast mode.", False),
    _user("user.accessibility.reduce_motion", "bool", "accessibility", "Reduce motion mode.", False),
    _user("user.accessibility.screen_reader_mode", "bool", "accessibility", "Screen reader mode.", False),
    # D5) Security preferences
    _user("user.security.require_face_login", "bool", "security", "Require face login for user.", False, min_role_to_edit="manager"),
    _user("user.security.session_timeout_seconds_override", "duration_seconds", "security", "Session timeout override.", None, {"min": 0}, min_role_to_edit="manager"),
]


SETTINGS_BY_KEY: dict[str, dict[str, Any]] = {item["key"]: item for item in SETTINGS_CATALOG}

