"""initial

Revision ID: 13500e977217
Revises: 
Create Date: 2026-01-20 15:42:09.803065

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13500e977217'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sqlite_autoincrement=True
    )
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_organizations_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_organizations_is_active'), ['is_active'], unique=False)

    op.create_table('permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sqlite_autoincrement=True
    )
    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_permissions_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_permissions_code'), ['code'], unique=True)

    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'name', name='uq_roles_org_name'),
    sqlite_autoincrement=True
    )
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.create_index('ix_roles_org_id', ['org_id'], unique=False)

    op.create_table('stores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=True),
    sa.Column('parent_store_id', sa.Integer(), nullable=True),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['parent_store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'code', name='uq_stores_org_code'),
    sa.UniqueConstraint('org_id', 'name', name='uq_stores_org_name'),
    sqlite_autoincrement=True
    )
    with op.batch_alter_table('stores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stores_code'), ['code'], unique=False)
        batch_op.create_index(batch_op.f('ix_stores_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stores_parent_store_id'), ['parent_store_id'], unique=False)

    op.create_table('document_sequences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('document_type', sa.String(length=32), nullable=False),
    sa.Column('next_number', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_id', 'document_type', name='uq_doc_sequences_store_type'),
    sqlite_autoincrement=True
    )
    with op.batch_alter_table('document_sequences', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_sequences_document_type'), ['document_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_sequences_store_id'), ['store_id'], unique=False)

    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price_cents', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_id', 'sku', name='uq_products_store_sku'),
    sqlite_autoincrement=True
    )
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.create_index('ix_products_store_active', ['store_id', 'is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_store_id'), ['store_id'], unique=False)
        batch_op.create_index('ix_products_store_name', ['store_id', 'name'], unique=False)

    op.create_table('registers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('register_number', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('location', sa.String(length=128), nullable=True),
    sa.Column('device_id', sa.String(length=128), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_id', 'register_number', name='uq_registers_store_number'),
    sqlite_autoincrement=True
    )
    with op.batch_alter_table('registers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_registers_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_registers_store_id'), ['store_id'], unique=False)

    op.create_table('role_permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.Column('granted_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_id', 'permission_id', name='uq_role_permissions'),
    sqlite_autoincrement=True
    )
    with op.batch_alter_table('role_permissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_role_permissions_permission_id'), ['permission_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_role_permissions_role_id'), ['role_id'], unique=False)

    op.create_table('store_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_id', 'key', name='uq_store_configs_store_key'),
    sqlite_autoincrement=True
    )
    with op.batch_alter_table('store_configs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_store_configs_store_id'), ['store_id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'email', name='uq_users_org_email'),
    sa.UniqueConstraint('org_id', 'username', name='uq_users_org_username'),
    sqlite_autoincrement=True
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('ix_users_org_id', ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=False)

    op.create_table('counts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('document_number', sa.String(length=64), nullable=False),
    sa.Column('count_type', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('total_variance_units', sa.Integer(), nullable=True),
    sa.Column('total_variance_cost_cents', sa.Integer(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('approved_by_user_id', sa.Integer(), nullable=True),
    sa.Column('posted_by_user_id', sa.Integer(), nullable=True),
    sa.Column('cancelled_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancellation_reason', sa.Text(), nullable=True),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['cancelled_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['posted_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_id', 'document_number', name='uq_counts_store_docnum'),
    sqlite_autoincrement=True
    )
    with op.batch_alter_table('counts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_counts_count_type'), ['count_type'], unique=False)
        batch_op.create_index('ix_counts_document_number', ['document_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_counts_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_counts_store_id'), ['store_id'], unique=False)

    op.create_table('inventory_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('quantity_delta', sa.Integer(), nullable=False),
    sa.Column('unit_cost_cents', sa.Integer(), nullable=True),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('sale_id', sa.String(length=64), nullable=True),
    sa.Column('sale_line_id', sa.String(length=64), nullable=True),
    sa.Column('unit_cost_cents_at_sale', sa.Integer(), nullable=True),
    sa.Column('cogs_cents', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('approved_by_user_id', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('posted_by_user_id', sa.Integer(), nullable=True),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('inventory_state', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_id', 'sale_id', 'sale_line_id', name='uq_invtx_store_sale_line'),
    sqlite_autoincrement=True
    )
    with op.batch_alter_table('inventory_transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inventory_transactions_inventory_state'), ['inventory_state'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_transactions_occurred_at'), ['occurred_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_transactions_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_transactions_sale_id'), ['sale_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_transactions_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_transactions_store_id'), ['store_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_transactions_type'), ['type'], unique=False)
        batch_op.create_index('ix_invtx_store_product_occurred', ['store_id', 'product_id', 'occurred_at'], unique=False)
        batch_op.create_index('ix_invtx_store_product_type_occurred', ['store_id', 'product_id', 'type', 'occurred_at'], unique=False)

    op.create_table('product_identifiers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('value', sa.String(length=128), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deactivated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'type', 'value', name='uq_identifier_org_type_value'),
    sqlite_autoincrement=True
    )
    with op.batch_alter_table('product_identifiers', schema=None) as batch_op:
        batch_op.create_index('ix_identifier_active', ['is_active'], unique=False)
        batch_op.create_index('ix_identifier_org_type_active', ['org_id', 'type', 'is_active'], unique=False)
        batch_op.create_index('ix_identifier_org_value', ['org_id', 'value'], unique=False)
        batch_op.create_index('ix_identifier_org_vendor_value', ['org_id', 'vendor_id', 'value'], unique=False)
        batch_op.create_index('ix_identifier_product', ['product_id'], unique=False)
        batch_op.create_index('ix_identifier_value', ['value'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_identifiers_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_identifiers_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_identifiers_store_id'), ['store_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_identifiers_type'), ['type'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_identifiers_vendor_id'), ['vendor_id'], unique=False)

    op.create_table('register_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('register_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('opened_by_user_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('opening_cash_cents', sa.Integer(), nullable=False),
    sa.Column('closing_cash_cents', sa.Integer(), nullable=True),
    sa.Column('expected_cash_cents', sa.Integer(), nullable=True),
    sa.Column('variance_cents', sa.Integer(), nullable=True),
    sa.Column('opened_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['opened_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['register_id'], ['registers.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sqlite_autoincrement=True
    )
    with op.batch_alter_table('register_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_register_sessions_opened_at'), ['opened_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_register_sessions_register_id'), ['register_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_register_sessions_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_register_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('security_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.Column('store_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('resource', sa.String(length=128), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sqlite_autoincrement=True
    )
    with op.batch_alter_table('security_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_security_events_event_type'), ['event_type'], unique=False)
        batch_op.create_index('ix_security_events_occurred', ['occurred_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_security_events_occurred_at'), ['occurred_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_security_events_org_id'), ['org_id'], unique=False)
        batch_op.create_index('ix_security_events_org_occurred', ['org_id', 'occurred_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_security_events_store_id'), ['store_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_security_events_success'), ['success'], unique=False)
        batch_op.create_index(batch_op.f('ix_security_events_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_security_events_user_type', ['user_id', 'event_type'], unique=False)

    op.create_table('session_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=True),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_revoked', sa.Boolean(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_reason', sa.String(length=255), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sqlite_autoincrement=True
    )
    with op.batch_alter_table('session_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_session_tokens_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_session_tokens_is_revoked'), ['is_revoked'], unique=False)
        batch_op.create_index(batch_op.f('ix_session_tokens_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_session_tokens_store_id'), ['store_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_session_tokens_token_hash'), ['token_hash'], unique=True)
        batch_op.create_index('ix_session_tokens_user_active', ['user_id', 'is_revoked'], unique=False)
        batch_op.create_index(batch_op.f('ix_session_tokens_user_id'), ['user_id'], unique=False)

    op.create_table('transfers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from_store_id', sa.Integer(), nullable=False),
    sa.Column('to_store_id', sa.Integer(), nullable=False),
    sa.Column('document_number', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('approved_by_user_id', sa.Integer(), nullable=True),
    sa.Column('shipped_by_user_id', sa.Integer(), nullable=True),
    sa.Column('received_by_user_id', sa.Integer(), nullable=True),
    sa.Column('cancelled_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('shipped_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancellation_reason', sa.Text(), nullable=True),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['cancelled_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['from_store_id'], ['stores.id'], ),
    sa.ForeignKeyConstraint(['received_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['shipped_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['to_store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('from_store_id', 'document_number', name='uq_transfers_store_docnum'),
    sqlite_autoincrement=True
    )
    with op.batch_alter_table('transfers', schema=None) as batch_op:
        batch_op.create_index('ix_transfers_document_number', ['document_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_transfers_from_store_id'), ['from_store_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transfers_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_transfers_to_store_id'), ['to_store_id'], unique=False)

    op.create_table('user_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'role_id', name='uq_user_roles'),
    sqlite_autoincrement=True
    )
    with op.batch_alter_table('user_roles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_roles_role_id'), ['role_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_roles_user_id'), ['user_id'], unique=False)

    op.create_table('count_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('count_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('expected_quantity', sa.Integer(), nullable=False),
    sa.Column('actual_quantity', sa.Integer(), nullable=False),
    sa.Column('variance_quantity', sa.Integer(), nullable=False),
    sa.Column('unit_cost_cents', sa.Integer(), nullable=True),
    sa.Column('variance_cost_cents', sa.Integer(), nullable=True),
    sa.Column('inventory_transaction_id', sa.Integer(), nullable=True),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['count_id'], ['counts.id'], ),
    sa.ForeignKeyConstraint(['inventory_transaction_id'], ['inventory_transactions.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('count_id', 'product_id', name='uq_count_lines_count_product'),
    sqlite_autoincrement=True
    )
    with op.batch_alter_table('count_lines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_count_lines_count_id'), ['count_id'], unique=False)

    op.create_table('sales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('document_number', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('voided_by_user_id', sa.Integer(), nullable=True),
    sa.Column('voided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('void_reason', sa.String(length=255), nullable=True),
    sa.Column('register_id', sa.Integer(), nullable=True),
    sa.Column('register_session_id', sa.Integer(), nullable=True),
    sa.Column('payment_status', sa.String(length=16), nullable=False),
    sa.Column('total_due_cents', sa.Integer(), nullable=True),
    sa.Column('total_paid_cents', sa.Integer(), nullable=False),
    sa.Column('change_due_cents', sa.Integer(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['register_id'], ['registers.id'], ),
    sa.ForeignKeyConstraint(['register_session_id'], ['register_sessions.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.ForeignKeyConstraint(['voided_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_id', 'document_number', name='uq_sales_store_docnum'),
    sqlite_autoincrement=True
    )
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.create_index('ix_sales_document_number', ['document_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_payment_status'), ['payment_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_register_id'), ['register_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_register_session_id'), ['register_session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_store_id'), ['store_id'], unique=False)
        batch_op.create_index('ix_sales_store_status_created', ['store_id', 'status', 'created_at'], unique=False)

    op.create_table('transfer_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transfer_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_cost_cents', sa.Integer(), nullable=True),
    sa.Column('out_transaction_id', sa.Integer(), nullable=True),
    sa.Column('in_transaction_id', sa.Integer(), nullable=True),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['in_transaction_id'], ['inventory_transactions.id'], ),
    sa.ForeignKeyConstraint(['out_transaction_id'], ['inventory_transactions.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['transfer_id'], ['transfers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sqlite_autoincrement=True
    )
    with op.batch_alter_table('transfer_lines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transfer_lines_transfer_id'), ['transfer_id'], unique=False)

    op.create_table('cash_drawer_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('register_session_id', sa.Integer(), nullable=False),
    sa.Column('register_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=True),
    sa.Column('sale_id', sa.Integer(), nullable=True),
    sa.Column('approved_by_user_id', sa.Integer(), nullable=True),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['register_id'], ['registers.id'], ),
    sa.ForeignKeyConstraint(['register_session_id'], ['register_sessions.id'], ),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sqlite_autoincrement=True
    )
    with op.batch_alter_table('cash_drawer_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cash_drawer_events_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_cash_drawer_events_occurred_at'), ['occurred_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_cash_drawer_events_register_id'), ['register_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cash_drawer_events_register_session_id'), ['register_session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cash_drawer_events_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_drawer_events_register_occurred', ['register_id', 'occurred_at'], unique=False)

    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sale_id', sa.Integer(), nullable=False),
    sa.Column('tender_type', sa.String(length=32), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('reference_number', sa.String(length=128), nullable=True),
    sa.Column('change_cents', sa.Integer(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('voided_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('voided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('void_reason', sa.String(length=255), nullable=True),
    sa.Column('register_id', sa.Integer(), nullable=True),
    sa.Column('register_session_id', sa.Integer(), nullable=True),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['register_id'], ['registers.id'], ),
    sa.ForeignKeyConstraint(['register_session_id'], ['register_sessions.id'], ),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.id'], ),
    sa.ForeignKeyConstraint(['voided_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sqlite_autoincrement=True
    )
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payments_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_created_by_user_id'), ['created_by_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_register_id'), ['register_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_register_session_id'), ['register_session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_sale_id'), ['sale_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_tender_type'), ['tender_type'], unique=False)

    op.create_table('returns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('document_number', sa.String(length=64), nullable=False),
    sa.Column('original_sale_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('restocking_fee_cents', sa.Integer(), nullable=False),
    sa.Column('refund_amount_cents', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('approved_by_user_id', sa.Integer(), nullable=True),
    sa.Column('completed_by_user_id', sa.Integer(), nullable=True),
    sa.Column('rejected_by_user_id', sa.Integer(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('register_id', sa.Integer(), nullable=True),
    sa.Column('register_session_id', sa.Integer(), nullable=True),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['completed_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['original_sale_id'], ['sales.id'], ),
    sa.ForeignKeyConstraint(['register_id'], ['registers.id'], ),
    sa.ForeignKeyConstraint(['register_session_id'], ['register_sessions.id'], ),
    sa.ForeignKeyConstraint(['rejected_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_id', 'document_number', name='uq_returns_store_docnum'),
    sqlite_autoincrement=True
    )
    with op.batch_alter_table('returns', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_returns_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_returns_created_by_user_id'), ['created_by_user_id'], unique=False)
        batch_op.create_index('ix_returns_document_number', ['document_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_returns_original_sale_id'), ['original_sale_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_returns_register_id'), ['register_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_returns_register_session_id'), ['register_session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_returns_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_returns_store_id'), ['store_id'], unique=False)
        batch_op.create_index('ix_returns_store_status_created', ['store_id', 'status', 'created_at'], unique=False)

    op.create_table('sale_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sale_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price_cents', sa.Integer(), nullable=False),
    sa.Column('line_total_cents', sa.Integer(), nullable=False),
    sa.Column('inventory_transaction_id', sa.Integer(), nullable=True),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['inventory_transaction_id'], ['inventory_transactions.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sqlite_autoincrement=True
    )
    with op.batch_alter_table('sale_lines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sale_lines_sale_id'), ['sale_id'], unique=False)

    op.create_table('master_ledger_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('event_category', sa.String(length=32), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('actor_user_id', sa.Integer(), nullable=True),
    sa.Column('register_id', sa.Integer(), nullable=True),
    sa.Column('register_session_id', sa.Integer(), nullable=True),
    sa.Column('sale_id', sa.Integer(), nullable=True),
    sa.Column('payment_id', sa.Integer(), nullable=True),
    sa.Column('return_id', sa.Integer(), nullable=True),
    sa.Column('transfer_id', sa.Integer(), nullable=True),
    sa.Column('count_id', sa.Integer(), nullable=True),
    sa.Column('cash_drawer_event_id', sa.Integer(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('payload', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['cash_drawer_event_id'], ['cash_drawer_events.id'], ),
    sa.ForeignKeyConstraint(['count_id'], ['counts.id'], ),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ),
    sa.ForeignKeyConstraint(['register_id'], ['registers.id'], ),
    sa.ForeignKeyConstraint(['register_session_id'], ['register_sessions.id'], ),
    sa.ForeignKeyConstraint(['return_id'], ['returns.id'], ),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.ForeignKeyConstraint(['transfer_id'], ['transfers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sqlite_autoincrement=True
    )
    with op.batch_alter_table('master_ledger_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_master_ledger_events_actor_user_id'), ['actor_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_master_ledger_events_cash_drawer_event_id'), ['cash_drawer_event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_master_ledger_events_count_id'), ['count_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_master_ledger_events_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_master_ledger_events_entity_type'), ['entity_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_master_ledger_events_event_category'), ['event_category'], unique=False)
        batch_op.create_index(batch_op.f('ix_master_ledger_events_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_master_ledger_events_occurred_at'), ['occurred_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_master_ledger_events_payment_id'), ['payment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_master_ledger_events_register_id'), ['register_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_master_ledger_events_register_session_id'), ['register_session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_master_ledger_events_return_id'), ['return_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_master_ledger_events_sale_id'), ['sale_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_master_ledger_events_store_id'), ['store_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_master_ledger_events_transfer_id'), ['transfer_id'], unique=False)
        batch_op.create_index('ix_master_ledger_store_occurred', ['store_id', 'occurred_at'], unique=False)

    op.create_table('payment_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payment_id', sa.Integer(), nullable=False),
    sa.Column('sale_id', sa.Integer(), nullable=False),
    sa.Column('transaction_type', sa.String(length=16), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('tender_type', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('register_id', sa.Integer(), nullable=True),
    sa.Column('register_session_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ),
    sa.ForeignKeyConstraint(['register_id'], ['registers.id'], ),
    sa.ForeignKeyConstraint(['register_session_id'], ['register_sessions.id'], ),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sqlite_autoincrement=True
    )
    with op.batch_alter_table('payment_transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payment_transactions_occurred_at'), ['occurred_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_transactions_payment_id'), ['payment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_transactions_register_id'), ['register_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_transactions_register_session_id'), ['register_session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_transactions_sale_id'), ['sale_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_transactions_tender_type'), ['tender_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_transactions_transaction_type'), ['transaction_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_transactions_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_payment_txns_occurred', ['occurred_at'], unique=False)
        batch_op.create_index('ix_payment_txns_sale_occurred', ['sale_id', 'occurred_at'], unique=False)

    op.create_table('return_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('return_id', sa.Integer(), nullable=False),
    sa.Column('original_sale_line_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price_cents', sa.Integer(), nullable=False),
    sa.Column('line_refund_cents', sa.Integer(), nullable=False),
    sa.Column('original_unit_cost_cents', sa.Integer(), nullable=True),
    sa.Column('original_cogs_cents', sa.Integer(), nullable=True),
    sa.Column('inventory_transaction_id', sa.Integer(), nullable=True),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['inventory_transaction_id'], ['inventory_transactions.id'], ),
    sa.ForeignKeyConstraint(['original_sale_line_id'], ['sale_lines.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['return_id'], ['returns.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sqlite_autoincrement=True
    )
    with op.batch_alter_table('return_lines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_return_lines_original_sale_line_id'), ['original_sale_line_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_return_lines_return_id'), ['return_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('return_lines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_return_lines_return_id'))
        batch_op.drop_index(batch_op.f('ix_return_lines_original_sale_line_id'))

    op.drop_table('return_lines')
    with op.batch_alter_table('payment_transactions', schema=None) as batch_op:
        batch_op.drop_index('ix_payment_txns_sale_occurred')
        batch_op.drop_index('ix_payment_txns_occurred')
        batch_op.drop_index(batch_op.f('ix_payment_transactions_user_id'))
        batch_op.drop_index(batch_op.f('ix_payment_transactions_transaction_type'))
        batch_op.drop_index(batch_op.f('ix_payment_transactions_tender_type'))
        batch_op.drop_index(batch_op.f('ix_payment_transactions_sale_id'))
        batch_op.drop_index(batch_op.f('ix_payment_transactions_register_session_id'))
        batch_op.drop_index(batch_op.f('ix_payment_transactions_register_id'))
        batch_op.drop_index(batch_op.f('ix_payment_transactions_payment_id'))
        batch_op.drop_index(batch_op.f('ix_payment_transactions_occurred_at'))

    op.drop_table('payment_transactions')
    with op.batch_alter_table('master_ledger_events', schema=None) as batch_op:
        batch_op.drop_index('ix_master_ledger_store_occurred')
        batch_op.drop_index(batch_op.f('ix_master_ledger_events_transfer_id'))
        batch_op.drop_index(batch_op.f('ix_master_ledger_events_store_id'))
        batch_op.drop_index(batch_op.f('ix_master_ledger_events_sale_id'))
        batch_op.drop_index(batch_op.f('ix_master_ledger_events_return_id'))
        batch_op.drop_index(batch_op.f('ix_master_ledger_events_register_session_id'))
        batch_op.drop_index(batch_op.f('ix_master_ledger_events_register_id'))
        batch_op.drop_index(batch_op.f('ix_master_ledger_events_payment_id'))
        batch_op.drop_index(batch_op.f('ix_master_ledger_events_occurred_at'))
        batch_op.drop_index(batch_op.f('ix_master_ledger_events_event_type'))
        batch_op.drop_index(batch_op.f('ix_master_ledger_events_event_category'))
        batch_op.drop_index(batch_op.f('ix_master_ledger_events_entity_type'))
        batch_op.drop_index(batch_op.f('ix_master_ledger_events_entity_id'))
        batch_op.drop_index(batch_op.f('ix_master_ledger_events_count_id'))
        batch_op.drop_index(batch_op.f('ix_master_ledger_events_cash_drawer_event_id'))
        batch_op.drop_index(batch_op.f('ix_master_ledger_events_actor_user_id'))

    op.drop_table('master_ledger_events')
    with op.batch_alter_table('sale_lines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sale_lines_sale_id'))

    op.drop_table('sale_lines')
    with op.batch_alter_table('returns', schema=None) as batch_op:
        batch_op.drop_index('ix_returns_store_status_created')
        batch_op.drop_index(batch_op.f('ix_returns_store_id'))
        batch_op.drop_index(batch_op.f('ix_returns_status'))
        batch_op.drop_index(batch_op.f('ix_returns_register_session_id'))
        batch_op.drop_index(batch_op.f('ix_returns_register_id'))
        batch_op.drop_index(batch_op.f('ix_returns_original_sale_id'))
        batch_op.drop_index('ix_returns_document_number')
        batch_op.drop_index(batch_op.f('ix_returns_created_by_user_id'))
        batch_op.drop_index(batch_op.f('ix_returns_created_at'))

    op.drop_table('returns')
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payments_tender_type'))
        batch_op.drop_index(batch_op.f('ix_payments_status'))
        batch_op.drop_index(batch_op.f('ix_payments_sale_id'))
        batch_op.drop_index(batch_op.f('ix_payments_register_session_id'))
        batch_op.drop_index(batch_op.f('ix_payments_register_id'))
        batch_op.drop_index(batch_op.f('ix_payments_created_by_user_id'))
        batch_op.drop_index(batch_op.f('ix_payments_created_at'))

    op.drop_table('payments')
    with op.batch_alter_table('cash_drawer_events', schema=None) as batch_op:
        batch_op.drop_index('ix_drawer_events_register_occurred')
        batch_op.drop_index(batch_op.f('ix_cash_drawer_events_user_id'))
        batch_op.drop_index(batch_op.f('ix_cash_drawer_events_register_session_id'))
        batch_op.drop_index(batch_op.f('ix_cash_drawer_events_register_id'))
        batch_op.drop_index(batch_op.f('ix_cash_drawer_events_occurred_at'))
        batch_op.drop_index(batch_op.f('ix_cash_drawer_events_event_type'))

    op.drop_table('cash_drawer_events')
    with op.batch_alter_table('transfer_lines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transfer_lines_transfer_id'))

    op.drop_table('transfer_lines')
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.drop_index('ix_sales_store_status_created')
        batch_op.drop_index(batch_op.f('ix_sales_store_id'))
        batch_op.drop_index(batch_op.f('ix_sales_status'))
        batch_op.drop_index(batch_op.f('ix_sales_register_session_id'))
        batch_op.drop_index(batch_op.f('ix_sales_register_id'))
        batch_op.drop_index(batch_op.f('ix_sales_payment_status'))
        batch_op.drop_index('ix_sales_document_number')

    op.drop_table('sales')
    with op.batch_alter_table('count_lines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_count_lines_count_id'))

    op.drop_table('count_lines')
    with op.batch_alter_table('user_roles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_roles_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_roles_role_id'))

    op.drop_table('user_roles')
    with op.batch_alter_table('transfers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transfers_to_store_id'))
        batch_op.drop_index(batch_op.f('ix_transfers_status'))
        batch_op.drop_index(batch_op.f('ix_transfers_from_store_id'))
        batch_op.drop_index('ix_transfers_document_number')

    op.drop_table('transfers')
    with op.batch_alter_table('session_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_session_tokens_user_id'))
        batch_op.drop_index('ix_session_tokens_user_active')
        batch_op.drop_index(batch_op.f('ix_session_tokens_token_hash'))
        batch_op.drop_index(batch_op.f('ix_session_tokens_store_id'))
        batch_op.drop_index(batch_op.f('ix_session_tokens_org_id'))
        batch_op.drop_index(batch_op.f('ix_session_tokens_is_revoked'))
        batch_op.drop_index(batch_op.f('ix_session_tokens_expires_at'))

    op.drop_table('session_tokens')
    with op.batch_alter_table('security_events', schema=None) as batch_op:
        batch_op.drop_index('ix_security_events_user_type')
        batch_op.drop_index(batch_op.f('ix_security_events_user_id'))
        batch_op.drop_index(batch_op.f('ix_security_events_success'))
        batch_op.drop_index(batch_op.f('ix_security_events_store_id'))
        batch_op.drop_index('ix_security_events_org_occurred')
        batch_op.drop_index(batch_op.f('ix_security_events_org_id'))
        batch_op.drop_index(batch_op.f('ix_security_events_occurred_at'))
        batch_op.drop_index('ix_security_events_occurred')
        batch_op.drop_index(batch_op.f('ix_security_events_event_type'))

    op.drop_table('security_events')
    with op.batch_alter_table('register_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_register_sessions_user_id'))
        batch_op.drop_index(batch_op.f('ix_register_sessions_status'))
        batch_op.drop_index(batch_op.f('ix_register_sessions_register_id'))
        batch_op.drop_index(batch_op.f('ix_register_sessions_opened_at'))

    op.drop_table('register_sessions')
    with op.batch_alter_table('product_identifiers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_identifiers_vendor_id'))
        batch_op.drop_index(batch_op.f('ix_product_identifiers_type'))
        batch_op.drop_index(batch_op.f('ix_product_identifiers_store_id'))
        batch_op.drop_index(batch_op.f('ix_product_identifiers_org_id'))
        batch_op.drop_index(batch_op.f('ix_product_identifiers_is_active'))
        batch_op.drop_index('ix_identifier_value')
        batch_op.drop_index('ix_identifier_product')
        batch_op.drop_index('ix_identifier_org_vendor_value')
        batch_op.drop_index('ix_identifier_org_value')
        batch_op.drop_index('ix_identifier_org_type_active')
        batch_op.drop_index('ix_identifier_active')

    op.drop_table('product_identifiers')
    with op.batch_alter_table('inventory_transactions', schema=None) as batch_op:
        batch_op.drop_index('ix_invtx_store_product_type_occurred')
        batch_op.drop_index('ix_invtx_store_product_occurred')
        batch_op.drop_index(batch_op.f('ix_inventory_transactions_type'))
        batch_op.drop_index(batch_op.f('ix_inventory_transactions_store_id'))
        batch_op.drop_index(batch_op.f('ix_inventory_transactions_status'))
        batch_op.drop_index(batch_op.f('ix_inventory_transactions_sale_id'))
        batch_op.drop_index(batch_op.f('ix_inventory_transactions_product_id'))
        batch_op.drop_index(batch_op.f('ix_inventory_transactions_occurred_at'))
        batch_op.drop_index(batch_op.f('ix_inventory_transactions_inventory_state'))

    op.drop_table('inventory_transactions')
    with op.batch_alter_table('counts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_counts_store_id'))
        batch_op.drop_index(batch_op.f('ix_counts_status'))
        batch_op.drop_index('ix_counts_document_number')
        batch_op.drop_index(batch_op.f('ix_counts_count_type'))

    op.drop_table('counts')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index('ix_users_org_id')

    op.drop_table('users')
    with op.batch_alter_table('store_configs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_store_configs_store_id'))

    op.drop_table('store_configs')
    with op.batch_alter_table('role_permissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_role_permissions_role_id'))
        batch_op.drop_index(batch_op.f('ix_role_permissions_permission_id'))

    op.drop_table('role_permissions')
    with op.batch_alter_table('registers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_registers_store_id'))
        batch_op.drop_index(batch_op.f('ix_registers_is_active'))

    op.drop_table('registers')
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index('ix_products_store_name')
        batch_op.drop_index(batch_op.f('ix_products_store_id'))
        batch_op.drop_index('ix_products_store_active')

    op.drop_table('products')
    with op.batch_alter_table('document_sequences', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_sequences_store_id'))
        batch_op.drop_index(batch_op.f('ix_document_sequences_document_type'))

    op.drop_table('document_sequences')
    with op.batch_alter_table('stores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stores_parent_store_id'))
        batch_op.drop_index(batch_op.f('ix_stores_org_id'))
        batch_op.drop_index(batch_op.f('ix_stores_code'))

    op.drop_table('stores')
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_index('ix_roles_org_id')

    op.drop_table('roles')
    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_permissions_code'))
        batch_op.drop_index(batch_op.f('ix_permissions_category'))

    op.drop_table('permissions')
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_organizations_is_active'))
        batch_op.drop_index(batch_op.f('ix_organizations_code'))

    op.drop_table('organizations')
    # ### end Alembic commands ###
