"""Phase 9: Add payments, payment_transactions, and update sales for payment tracking

Revision ID: 26367ddf3599
Revises: 3e5954ad8d19
Create Date: 2026-01-14 17:56:06.453452

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26367ddf3599'
down_revision = '3e5954ad8d19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sqlite_autoincrement=True
    )
    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_permissions_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_permissions_code'), ['code'], unique=True)

    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sqlite_autoincrement=True
    )
    op.create_table('stores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sqlite_autoincrement=True
    )
    op.create_table('master_ledger_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sqlite_autoincrement=True
    )
    with op.batch_alter_table('master_ledger_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_master_ledger_events_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_master_ledger_events_entity_type'), ['entity_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_master_ledger_events_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_master_ledger_events_occurred_at'), ['occurred_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_master_ledger_events_store_id'), ['store_id'], unique=False)

    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price_cents', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_id', 'sku', name='uq_products_store_sku'),
    sqlite_autoincrement=True
    )
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_products_store_id'), ['store_id'], unique=False)
        batch_op.create_index('ix_products_store_name', ['store_id', 'name'], unique=False)

    op.create_table('registers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('register_number', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('location', sa.String(length=128), nullable=True),
    sa.Column('device_id', sa.String(length=128), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_id', 'register_number', name='uq_registers_store_number'),
    sqlite_autoincrement=True
    )
    with op.batch_alter_table('registers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_registers_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_registers_store_id'), ['store_id'], unique=False)

    op.create_table('role_permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.Column('granted_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_id', 'permission_id', name='uq_role_permissions'),
    sqlite_autoincrement=True
    )
    with op.batch_alter_table('role_permissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_role_permissions_permission_id'), ['permission_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_role_permissions_role_id'), ['role_id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sqlite_autoincrement=True
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('inventory_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('quantity_delta', sa.Integer(), nullable=False),
    sa.Column('unit_cost_cents', sa.Integer(), nullable=True),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('sale_id', sa.String(length=64), nullable=True),
    sa.Column('sale_line_id', sa.String(length=64), nullable=True),
    sa.Column('unit_cost_cents_at_sale', sa.Integer(), nullable=True),
    sa.Column('cogs_cents', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('approved_by_user_id', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('posted_by_user_id', sa.Integer(), nullable=True),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_id', 'sale_id', 'sale_line_id', name='uq_invtx_store_sale_line'),
    sqlite_autoincrement=True
    )
    with op.batch_alter_table('inventory_transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inventory_transactions_occurred_at'), ['occurred_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_transactions_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_transactions_sale_id'), ['sale_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_transactions_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_transactions_store_id'), ['store_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_transactions_type'), ['type'], unique=False)
        batch_op.create_index('ix_invtx_store_product_occurred', ['store_id', 'product_id', 'occurred_at'], unique=False)
        batch_op.create_index('ix_invtx_store_product_type_occurred', ['store_id', 'product_id', 'type', 'occurred_at'], unique=False)

    op.create_table('product_identifiers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('value', sa.String(length=128), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('type', 'value', name='uq_identifier_type_value'),
    sqlite_autoincrement=True
    )
    with op.batch_alter_table('product_identifiers', schema=None) as batch_op:
        batch_op.create_index('ix_identifier_product', ['product_id'], unique=False)
        batch_op.create_index('ix_identifier_value', ['value'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_identifiers_type'), ['type'], unique=False)

    op.create_table('register_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('register_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('opening_cash_cents', sa.Integer(), nullable=False),
    sa.Column('closing_cash_cents', sa.Integer(), nullable=True),
    sa.Column('expected_cash_cents', sa.Integer(), nullable=True),
    sa.Column('variance_cents', sa.Integer(), nullable=True),
    sa.Column('opened_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['register_id'], ['registers.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sqlite_autoincrement=True
    )
    with op.batch_alter_table('register_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_register_sessions_opened_at'), ['opened_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_register_sessions_register_id'), ['register_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_register_sessions_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_register_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('security_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('resource', sa.String(length=128), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sqlite_autoincrement=True
    )
    with op.batch_alter_table('security_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_security_events_event_type'), ['event_type'], unique=False)
        batch_op.create_index('ix_security_events_occurred', ['occurred_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_security_events_occurred_at'), ['occurred_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_security_events_success'), ['success'], unique=False)
        batch_op.create_index(batch_op.f('ix_security_events_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_security_events_user_type', ['user_id', 'event_type'], unique=False)

    op.create_table('session_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_revoked', sa.Boolean(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_reason', sa.String(length=255), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sqlite_autoincrement=True
    )
    with op.batch_alter_table('session_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_session_tokens_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_session_tokens_is_revoked'), ['is_revoked'], unique=False)
        batch_op.create_index(batch_op.f('ix_session_tokens_token_hash'), ['token_hash'], unique=True)
        batch_op.create_index('ix_session_tokens_user_active', ['user_id', 'is_revoked'], unique=False)
        batch_op.create_index(batch_op.f('ix_session_tokens_user_id'), ['user_id'], unique=False)

    op.create_table('user_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'role_id', name='uq_user_roles'),
    sqlite_autoincrement=True
    )
    with op.batch_alter_table('user_roles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_roles_role_id'), ['role_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_roles_user_id'), ['user_id'], unique=False)

    op.create_table('sales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('document_number', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('register_id', sa.Integer(), nullable=True),
    sa.Column('register_session_id', sa.Integer(), nullable=True),
    sa.Column('payment_status', sa.String(length=16), nullable=False),
    sa.Column('total_due_cents', sa.Integer(), nullable=True),
    sa.Column('total_paid_cents', sa.Integer(), nullable=False),
    sa.Column('change_due_cents', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['register_id'], ['registers.id'], ),
    sa.ForeignKeyConstraint(['register_session_id'], ['register_sessions.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_id', 'document_number', name='uq_sales_store_docnum'),
    sqlite_autoincrement=True
    )
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sales_payment_status'), ['payment_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_register_id'), ['register_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_register_session_id'), ['register_session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_store_id'), ['store_id'], unique=False)

    op.create_table('cash_drawer_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('register_session_id', sa.Integer(), nullable=False),
    sa.Column('register_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=True),
    sa.Column('sale_id', sa.Integer(), nullable=True),
    sa.Column('approved_by_user_id', sa.Integer(), nullable=True),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['register_id'], ['registers.id'], ),
    sa.ForeignKeyConstraint(['register_session_id'], ['register_sessions.id'], ),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sqlite_autoincrement=True
    )
    with op.batch_alter_table('cash_drawer_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cash_drawer_events_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_cash_drawer_events_occurred_at'), ['occurred_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_cash_drawer_events_register_id'), ['register_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cash_drawer_events_register_session_id'), ['register_session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cash_drawer_events_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_drawer_events_register_occurred', ['register_id', 'occurred_at'], unique=False)

    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sale_id', sa.Integer(), nullable=False),
    sa.Column('tender_type', sa.String(length=32), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('reference_number', sa.String(length=128), nullable=True),
    sa.Column('change_cents', sa.Integer(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('voided_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('voided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('void_reason', sa.String(length=255), nullable=True),
    sa.Column('register_id', sa.Integer(), nullable=True),
    sa.Column('register_session_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['register_id'], ['registers.id'], ),
    sa.ForeignKeyConstraint(['register_session_id'], ['register_sessions.id'], ),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.id'], ),
    sa.ForeignKeyConstraint(['voided_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sqlite_autoincrement=True
    )
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payments_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_created_by_user_id'), ['created_by_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_register_id'), ['register_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_register_session_id'), ['register_session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_sale_id'), ['sale_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_tender_type'), ['tender_type'], unique=False)

    op.create_table('sale_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sale_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price_cents', sa.Integer(), nullable=False),
    sa.Column('line_total_cents', sa.Integer(), nullable=False),
    sa.Column('inventory_transaction_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['inventory_transaction_id'], ['inventory_transactions.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sqlite_autoincrement=True
    )
    with op.batch_alter_table('sale_lines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sale_lines_sale_id'), ['sale_id'], unique=False)

    op.create_table('payment_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payment_id', sa.Integer(), nullable=False),
    sa.Column('sale_id', sa.Integer(), nullable=False),
    sa.Column('transaction_type', sa.String(length=16), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('tender_type', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('register_id', sa.Integer(), nullable=True),
    sa.Column('register_session_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ),
    sa.ForeignKeyConstraint(['register_id'], ['registers.id'], ),
    sa.ForeignKeyConstraint(['register_session_id'], ['register_sessions.id'], ),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sqlite_autoincrement=True
    )
    with op.batch_alter_table('payment_transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payment_transactions_occurred_at'), ['occurred_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_transactions_payment_id'), ['payment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_transactions_register_id'), ['register_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_transactions_register_session_id'), ['register_session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_transactions_sale_id'), ['sale_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_transactions_tender_type'), ['tender_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_transactions_transaction_type'), ['transaction_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_transactions_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_payment_txns_occurred', ['occurred_at'], unique=False)
        batch_op.create_index('ix_payment_txns_sale_occurred', ['sale_id', 'occurred_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment_transactions', schema=None) as batch_op:
        batch_op.drop_index('ix_payment_txns_sale_occurred')
        batch_op.drop_index('ix_payment_txns_occurred')
        batch_op.drop_index(batch_op.f('ix_payment_transactions_user_id'))
        batch_op.drop_index(batch_op.f('ix_payment_transactions_transaction_type'))
        batch_op.drop_index(batch_op.f('ix_payment_transactions_tender_type'))
        batch_op.drop_index(batch_op.f('ix_payment_transactions_sale_id'))
        batch_op.drop_index(batch_op.f('ix_payment_transactions_register_session_id'))
        batch_op.drop_index(batch_op.f('ix_payment_transactions_register_id'))
        batch_op.drop_index(batch_op.f('ix_payment_transactions_payment_id'))
        batch_op.drop_index(batch_op.f('ix_payment_transactions_occurred_at'))

    op.drop_table('payment_transactions')
    with op.batch_alter_table('sale_lines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sale_lines_sale_id'))

    op.drop_table('sale_lines')
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payments_tender_type'))
        batch_op.drop_index(batch_op.f('ix_payments_status'))
        batch_op.drop_index(batch_op.f('ix_payments_sale_id'))
        batch_op.drop_index(batch_op.f('ix_payments_register_session_id'))
        batch_op.drop_index(batch_op.f('ix_payments_register_id'))
        batch_op.drop_index(batch_op.f('ix_payments_created_by_user_id'))
        batch_op.drop_index(batch_op.f('ix_payments_created_at'))

    op.drop_table('payments')
    with op.batch_alter_table('cash_drawer_events', schema=None) as batch_op:
        batch_op.drop_index('ix_drawer_events_register_occurred')
        batch_op.drop_index(batch_op.f('ix_cash_drawer_events_user_id'))
        batch_op.drop_index(batch_op.f('ix_cash_drawer_events_register_session_id'))
        batch_op.drop_index(batch_op.f('ix_cash_drawer_events_register_id'))
        batch_op.drop_index(batch_op.f('ix_cash_drawer_events_occurred_at'))
        batch_op.drop_index(batch_op.f('ix_cash_drawer_events_event_type'))

    op.drop_table('cash_drawer_events')
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sales_store_id'))
        batch_op.drop_index(batch_op.f('ix_sales_status'))
        batch_op.drop_index(batch_op.f('ix_sales_register_session_id'))
        batch_op.drop_index(batch_op.f('ix_sales_register_id'))
        batch_op.drop_index(batch_op.f('ix_sales_payment_status'))

    op.drop_table('sales')
    with op.batch_alter_table('user_roles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_roles_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_roles_role_id'))

    op.drop_table('user_roles')
    with op.batch_alter_table('session_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_session_tokens_user_id'))
        batch_op.drop_index('ix_session_tokens_user_active')
        batch_op.drop_index(batch_op.f('ix_session_tokens_token_hash'))
        batch_op.drop_index(batch_op.f('ix_session_tokens_is_revoked'))
        batch_op.drop_index(batch_op.f('ix_session_tokens_expires_at'))

    op.drop_table('session_tokens')
    with op.batch_alter_table('security_events', schema=None) as batch_op:
        batch_op.drop_index('ix_security_events_user_type')
        batch_op.drop_index(batch_op.f('ix_security_events_user_id'))
        batch_op.drop_index(batch_op.f('ix_security_events_success'))
        batch_op.drop_index(batch_op.f('ix_security_events_occurred_at'))
        batch_op.drop_index('ix_security_events_occurred')
        batch_op.drop_index(batch_op.f('ix_security_events_event_type'))

    op.drop_table('security_events')
    with op.batch_alter_table('register_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_register_sessions_user_id'))
        batch_op.drop_index(batch_op.f('ix_register_sessions_status'))
        batch_op.drop_index(batch_op.f('ix_register_sessions_register_id'))
        batch_op.drop_index(batch_op.f('ix_register_sessions_opened_at'))

    op.drop_table('register_sessions')
    with op.batch_alter_table('product_identifiers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_identifiers_type'))
        batch_op.drop_index('ix_identifier_value')
        batch_op.drop_index('ix_identifier_product')

    op.drop_table('product_identifiers')
    with op.batch_alter_table('inventory_transactions', schema=None) as batch_op:
        batch_op.drop_index('ix_invtx_store_product_type_occurred')
        batch_op.drop_index('ix_invtx_store_product_occurred')
        batch_op.drop_index(batch_op.f('ix_inventory_transactions_type'))
        batch_op.drop_index(batch_op.f('ix_inventory_transactions_store_id'))
        batch_op.drop_index(batch_op.f('ix_inventory_transactions_status'))
        batch_op.drop_index(batch_op.f('ix_inventory_transactions_sale_id'))
        batch_op.drop_index(batch_op.f('ix_inventory_transactions_product_id'))
        batch_op.drop_index(batch_op.f('ix_inventory_transactions_occurred_at'))

    op.drop_table('inventory_transactions')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))

    op.drop_table('users')
    with op.batch_alter_table('role_permissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_role_permissions_role_id'))
        batch_op.drop_index(batch_op.f('ix_role_permissions_permission_id'))

    op.drop_table('role_permissions')
    with op.batch_alter_table('registers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_registers_store_id'))
        batch_op.drop_index(batch_op.f('ix_registers_is_active'))

    op.drop_table('registers')
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index('ix_products_store_name')
        batch_op.drop_index(batch_op.f('ix_products_store_id'))

    op.drop_table('products')
    with op.batch_alter_table('master_ledger_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_master_ledger_events_store_id'))
        batch_op.drop_index(batch_op.f('ix_master_ledger_events_occurred_at'))
        batch_op.drop_index(batch_op.f('ix_master_ledger_events_event_type'))
        batch_op.drop_index(batch_op.f('ix_master_ledger_events_entity_type'))
        batch_op.drop_index(batch_op.f('ix_master_ledger_events_entity_id'))

    op.drop_table('master_ledger_events')
    op.drop_table('stores')
    op.drop_table('roles')
    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_permissions_code'))
        batch_op.drop_index(batch_op.f('ix_permissions_category'))

    op.drop_table('permissions')
    # ### end Alembic commands ###
