"""Add CashDrawer and Printer models

Revision ID: 2f278182c655
Revises: 20260211_drop_reg_device
Create Date: 2026-02-11 15:04:17.226385

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f278182c655'
down_revision = '20260211_drop_reg_device'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cash_drawers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('register_id', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=True),
    sa.Column('serial_number', sa.String(length=128), nullable=True),
    sa.Column('connection_type', sa.String(length=32), nullable=True),
    sa.Column('connection_address', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['register_id'], ['registers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('register_id', name='uq_cash_drawers_register'),
    sqlite_autoincrement=True
    )
    with op.batch_alter_table('cash_drawers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cash_drawers_register_id'), ['register_id'], unique=False)

    op.create_table('printers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('register_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('printer_type', sa.String(length=32), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=True),
    sa.Column('serial_number', sa.String(length=128), nullable=True),
    sa.Column('connection_type', sa.String(length=32), nullable=True),
    sa.Column('connection_address', sa.String(length=255), nullable=True),
    sa.Column('paper_width_mm', sa.Integer(), nullable=True),
    sa.Column('supports_cut', sa.Boolean(), nullable=False),
    sa.Column('supports_cash_drawer', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['register_id'], ['registers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sqlite_autoincrement=True
    )
    with op.batch_alter_table('printers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_printers_printer_type'), ['printer_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_printers_register_id'), ['register_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('printers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_printers_register_id'))
        batch_op.drop_index(batch_op.f('ix_printers_printer_type'))

    op.drop_table('printers')
    with op.batch_alter_table('cash_drawers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cash_drawers_register_id'))

    op.drop_table('cash_drawers')
    # ### end Alembic commands ###
