"""Phase 8: Add registers, register_sessions, and cash_drawer_events tables

Revision ID: 3e5954ad8d19
Revises: 7b6e4094dce4
Create Date: 2026-01-14 17:37:27.345299

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e5954ad8d19'
down_revision = '7b6e4094dce4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('registers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('register_number', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('location', sa.String(length=128), nullable=True),
    sa.Column('device_id', sa.String(length=128), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_id', 'register_number', name='uq_registers_store_number'),
    sqlite_autoincrement=True
    )
    with op.batch_alter_table('registers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_registers_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_registers_store_id'), ['store_id'], unique=False)

    op.create_table('register_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('register_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('opening_cash_cents', sa.Integer(), nullable=False),
    sa.Column('closing_cash_cents', sa.Integer(), nullable=True),
    sa.Column('expected_cash_cents', sa.Integer(), nullable=True),
    sa.Column('variance_cents', sa.Integer(), nullable=True),
    sa.Column('opened_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['register_id'], ['registers.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sqlite_autoincrement=True
    )
    with op.batch_alter_table('register_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_register_sessions_opened_at'), ['opened_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_register_sessions_register_id'), ['register_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_register_sessions_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_register_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('cash_drawer_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('register_session_id', sa.Integer(), nullable=False),
    sa.Column('register_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=True),
    sa.Column('sale_id', sa.Integer(), nullable=True),
    sa.Column('approved_by_user_id', sa.Integer(), nullable=True),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['register_id'], ['registers.id'], ),
    sa.ForeignKeyConstraint(['register_session_id'], ['register_sessions.id'], ),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sqlite_autoincrement=True
    )
    with op.batch_alter_table('cash_drawer_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cash_drawer_events_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_cash_drawer_events_occurred_at'), ['occurred_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_cash_drawer_events_register_id'), ['register_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cash_drawer_events_register_session_id'), ['register_session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cash_drawer_events_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_drawer_events_register_occurred', ['register_id', 'occurred_at'], unique=False)

    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.add_column(sa.Column('register_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('register_session_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_sales_register_id'), ['register_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_register_session_id'), ['register_session_id'], unique=False)
        batch_op.create_foreign_key('fk_sales_register_session_id', 'register_sessions', ['register_session_id'], ['id'])
        batch_op.create_foreign_key('fk_sales_register_id', 'registers', ['register_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_sales_register_session_id'))
        batch_op.drop_index(batch_op.f('ix_sales_register_id'))
        batch_op.drop_column('register_session_id')
        batch_op.drop_column('register_id')

    with op.batch_alter_table('cash_drawer_events', schema=None) as batch_op:
        batch_op.drop_index('ix_drawer_events_register_occurred')
        batch_op.drop_index(batch_op.f('ix_cash_drawer_events_user_id'))
        batch_op.drop_index(batch_op.f('ix_cash_drawer_events_register_session_id'))
        batch_op.drop_index(batch_op.f('ix_cash_drawer_events_register_id'))
        batch_op.drop_index(batch_op.f('ix_cash_drawer_events_occurred_at'))
        batch_op.drop_index(batch_op.f('ix_cash_drawer_events_event_type'))

    op.drop_table('cash_drawer_events')
    with op.batch_alter_table('register_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_register_sessions_user_id'))
        batch_op.drop_index(batch_op.f('ix_register_sessions_status'))
        batch_op.drop_index(batch_op.f('ix_register_sessions_register_id'))
        batch_op.drop_index(batch_op.f('ix_register_sessions_opened_at'))

    op.drop_table('register_sessions')
    with op.batch_alter_table('registers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_registers_store_id'))
        batch_op.drop_index(batch_op.f('ix_registers_is_active'))

    op.drop_table('registers')
    # ### end Alembic commands ###
