# Overview: Alembic migration for 6 add session tokens table for.

"""Add session_tokens table for secure authentication

Revision ID: 46b132a5b02e
Revises: 361a2c35d372
Create Date: 2026-01-14 07:30:44.940745

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46b132a5b02e'
down_revision = '361a2c35d372'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('session_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_revoked', sa.Boolean(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_reason', sa.String(length=255), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sqlite_autoincrement=True
    )
    with op.batch_alter_table('session_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_session_tokens_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_session_tokens_is_revoked'), ['is_revoked'], unique=False)
        batch_op.create_index(batch_op.f('ix_session_tokens_token_hash'), ['token_hash'], unique=True)
        batch_op.create_index('ix_session_tokens_user_active', ['user_id', 'is_revoked'], unique=False)
        batch_op.create_index(batch_op.f('ix_session_tokens_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('session_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_session_tokens_user_id'))
        batch_op.drop_index('ix_session_tokens_user_active')
        batch_op.drop_index(batch_op.f('ix_session_tokens_token_hash'))
        batch_op.drop_index(batch_op.f('ix_session_tokens_is_revoked'))
        batch_op.drop_index(batch_op.f('ix_session_tokens_expires_at'))

    op.drop_table('session_tokens')
    # ### end Alembic commands ###
