"""phase2_models_overhaul

Revision ID: 8b4807ada400
Revises: 20260120_major
Create Date: 2026-02-09 11:49:23.319597

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b4807ada400'
down_revision = '20260120_major'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('announcements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('priority', sa.String(length=16), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('target_type', sa.String(length=16), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('display_type', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sqlite_autoincrement=True
    )
    with op.batch_alter_table('announcements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_announcements_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_announcements_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_announcements_store_id'), ['store_id'], unique=False)

    op.create_table('device_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('updated_by_user_id', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['registers.id'], ),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_id', 'key', name='uq_device_settings_key'),
    sqlite_autoincrement=True
    )
    with op.batch_alter_table('device_settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_device_settings_device_id'), ['device_id'], unique=False)

    op.create_table('organization_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('updated_by_user_id', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'key', name='uq_org_settings_key'),
    sqlite_autoincrement=True
    )
    with op.batch_alter_table('organization_settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_organization_settings_org_id'), ['org_id'], unique=False)

    op.create_table('promotions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('promo_type', sa.String(length=32), nullable=False),
    sa.Column('discount_value', sa.Integer(), nullable=False),
    sa.Column('applies_to', sa.String(length=32), nullable=False),
    sa.Column('product_ids', sa.Text(), nullable=True),
    sa.Column('min_quantity', sa.Integer(), nullable=True),
    sa.Column('min_amount_cents', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sqlite_autoincrement=True
    )
    with op.batch_alter_table('promotions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_promotions_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_promotions_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_promotions_store_id'), ['store_id'], unique=False)

    op.create_table('reminders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('target_type', sa.String(length=16), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('repeat_type', sa.String(length=16), nullable=False),
    sa.Column('repeat_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('display_type', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sqlite_autoincrement=True
    )
    with op.batch_alter_table('reminders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reminders_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_reminders_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reminders_store_id'), ['store_id'], unique=False)

    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('assigned_to_user_id', sa.Integer(), nullable=True),
    sa.Column('assigned_to_register_id', sa.Integer(), nullable=True),
    sa.Column('task_type', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('deferred_reason', sa.Text(), nullable=True),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to_register_id'], ['registers.id'], ),
    sa.ForeignKeyConstraint(['assigned_to_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sqlite_autoincrement=True
    )
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tasks_assigned_to_register_id'), ['assigned_to_register_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_assigned_to_user_id'), ['assigned_to_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_store_id'), ['store_id'], unique=False)

    with op.batch_alter_table('counts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('imported_from_batch_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_counts_imported_from_batch_id'), ['imported_from_batch_id'], unique=False)
        batch_op.create_foreign_key('fk_imported_batch', 'import_batches', ['imported_from_batch_id'], ['id'])

    with op.batch_alter_table('import_entity_mappings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_import_mapping_batch_id'))
        batch_op.create_index(batch_op.f('ix_import_entity_mappings_batch_id'), ['batch_id'], unique=False)

    with op.batch_alter_table('import_staging_rows', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_import_staging_batch_id'))
        batch_op.drop_index(batch_op.f('ix_import_staging_foreign_id'))
        batch_op.drop_index(batch_op.f('ix_import_staging_mapping_status'))
        batch_op.drop_index(batch_op.f('ix_import_staging_posting_status'))
        batch_op.create_index(batch_op.f('ix_import_staging_rows_batch_id'), ['batch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_import_staging_rows_foreign_id'), ['foreign_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_import_staging_rows_mapping_status'), ['mapping_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_import_staging_rows_posting_status'), ['posting_status'], unique=False)

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('imported_from_batch_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_products_imported_from_batch_id'), ['imported_from_batch_id'], unique=False)
        batch_op.create_foreign_key('fk_imported_batch', 'import_batches', ['imported_from_batch_id'], ['id'])

    with op.batch_alter_table('receive_document_lines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_receive_lines_document'))
        batch_op.drop_index(batch_op.f('ix_receive_lines_product'))
        batch_op.create_index(batch_op.f('ix_receive_document_lines_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_receive_document_lines_receive_document_id'), ['receive_document_id'], unique=False)

    with op.batch_alter_table('receive_documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('imported_from_batch_id', sa.Integer(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_receive_docs_created_by'))
        batch_op.drop_index(batch_op.f('ix_receive_docs_receive_type'))
        batch_op.drop_index(batch_op.f('ix_receive_docs_status'))
        batch_op.drop_index(batch_op.f('ix_receive_docs_store_id'))
        batch_op.create_index(batch_op.f('ix_receive_documents_created_by_user_id'), ['created_by_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_receive_documents_imported_from_batch_id'), ['imported_from_batch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_receive_documents_receive_type'), ['receive_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_receive_documents_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_receive_documents_store_id'), ['store_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_receive_documents_vendor_id'), ['vendor_id'], unique=False)
        batch_op.create_foreign_key('fk_imported_batch', 'import_batches', ['imported_from_batch_id'], ['id'])

    with op.batch_alter_table('returns', schema=None) as batch_op:
        batch_op.add_column(sa.Column('imported_from_batch_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_returns_imported_from_batch_id'), ['imported_from_batch_id'], unique=False)
        batch_op.create_foreign_key('fk_imported_batch', 'import_batches', ['imported_from_batch_id'], ['id'])

    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.add_column(sa.Column('imported_from_batch_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_sales_imported_from_batch_id'), ['imported_from_batch_id'], unique=False)
        batch_op.create_foreign_key('fk_imported_batch', 'import_batches', ['imported_from_batch_id'], ['id'])

    with op.batch_alter_table('session_tokens', schema=None) as batch_op:
        batch_op.alter_column('org_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('stores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timezone', sa.String(length=64), nullable=False, server_default='UTC'))
        batch_op.add_column(sa.Column('tax_rate_bps', sa.Integer(), nullable=False, server_default='0'))

    with op.batch_alter_table('time_clock_breaks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_time_clock_breaks_time_clock_entry_id'), ['time_clock_entry_id'], unique=False)

    with op.batch_alter_table('time_clock_corrections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_time_clock_corrections_time_clock_entry_id'), ['time_clock_entry_id'], unique=False)

    with op.batch_alter_table('time_clock_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_time_clock_register_session'))
        batch_op.drop_index(batch_op.f('ix_time_clock_status'))
        batch_op.drop_index(batch_op.f('ix_time_clock_store_id'))
        batch_op.drop_index(batch_op.f('ix_time_clock_user_id'))
        batch_op.create_index(batch_op.f('ix_time_clock_entries_register_session_id'), ['register_session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_time_clock_entries_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_time_clock_entries_store_id'), ['store_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_time_clock_entries_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('transfers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('imported_from_batch_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_transfers_imported_from_batch_id'), ['imported_from_batch_id'], unique=False)
        batch_op.create_foreign_key('fk_imported_batch', 'import_batches', ['imported_from_batch_id'], ['id'])

    with op.batch_alter_table('user_permission_overrides', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_perm_overrides_active'))
        batch_op.drop_index(batch_op.f('ix_user_perm_overrides_code'))
        batch_op.create_index(batch_op.f('ix_user_permission_overrides_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_permission_overrides_permission_code'), ['permission_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_permission_overrides_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_developer', sa.Boolean(), nullable=False, server_default='0'))
        batch_op.alter_column('org_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('vendors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vendors_is_active'), ['is_active'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vendors_is_active'))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('org_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('is_developer')

    with op.batch_alter_table('user_permission_overrides', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_permission_overrides_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_permission_overrides_permission_code'))
        batch_op.drop_index(batch_op.f('ix_user_permission_overrides_is_active'))
        batch_op.create_index(batch_op.f('ix_user_perm_overrides_code'), ['permission_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_perm_overrides_active'), ['is_active'], unique=False)

    with op.batch_alter_table('transfers', schema=None) as batch_op:
        batch_op.drop_constraint('fk_imported_batch', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_transfers_imported_from_batch_id'))
        batch_op.drop_column('imported_from_batch_id')

    with op.batch_alter_table('time_clock_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_time_clock_entries_user_id'))
        batch_op.drop_index(batch_op.f('ix_time_clock_entries_store_id'))
        batch_op.drop_index(batch_op.f('ix_time_clock_entries_status'))
        batch_op.drop_index(batch_op.f('ix_time_clock_entries_register_session_id'))
        batch_op.create_index(batch_op.f('ix_time_clock_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_time_clock_store_id'), ['store_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_time_clock_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_time_clock_register_session'), ['register_session_id'], unique=False)

    with op.batch_alter_table('time_clock_corrections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_time_clock_corrections_time_clock_entry_id'))

    with op.batch_alter_table('time_clock_breaks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_time_clock_breaks_time_clock_entry_id'))

    with op.batch_alter_table('stores', schema=None) as batch_op:
        batch_op.drop_column('tax_rate_bps')
        batch_op.drop_column('timezone')

    with op.batch_alter_table('session_tokens', schema=None) as batch_op:
        batch_op.alter_column('org_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.drop_constraint('fk_imported_batch', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_sales_imported_from_batch_id'))
        batch_op.drop_column('imported_from_batch_id')

    with op.batch_alter_table('returns', schema=None) as batch_op:
        batch_op.drop_constraint('fk_imported_batch', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_returns_imported_from_batch_id'))
        batch_op.drop_column('imported_from_batch_id')

    with op.batch_alter_table('receive_documents', schema=None) as batch_op:
        batch_op.drop_constraint('fk_imported_batch', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_receive_documents_vendor_id'))
        batch_op.drop_index(batch_op.f('ix_receive_documents_store_id'))
        batch_op.drop_index(batch_op.f('ix_receive_documents_status'))
        batch_op.drop_index(batch_op.f('ix_receive_documents_receive_type'))
        batch_op.drop_index(batch_op.f('ix_receive_documents_imported_from_batch_id'))
        batch_op.drop_index(batch_op.f('ix_receive_documents_created_by_user_id'))
        batch_op.create_index(batch_op.f('ix_receive_docs_store_id'), ['store_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_receive_docs_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_receive_docs_receive_type'), ['receive_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_receive_docs_created_by'), ['created_by_user_id'], unique=False)
        batch_op.drop_column('imported_from_batch_id')

    with op.batch_alter_table('receive_document_lines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_receive_document_lines_receive_document_id'))
        batch_op.drop_index(batch_op.f('ix_receive_document_lines_product_id'))
        batch_op.create_index(batch_op.f('ix_receive_lines_product'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_receive_lines_document'), ['receive_document_id'], unique=False)

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_constraint('fk_imported_batch', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_products_imported_from_batch_id'))
        batch_op.drop_column('imported_from_batch_id')

    with op.batch_alter_table('import_staging_rows', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_import_staging_rows_posting_status'))
        batch_op.drop_index(batch_op.f('ix_import_staging_rows_mapping_status'))
        batch_op.drop_index(batch_op.f('ix_import_staging_rows_foreign_id'))
        batch_op.drop_index(batch_op.f('ix_import_staging_rows_batch_id'))
        batch_op.create_index(batch_op.f('ix_import_staging_posting_status'), ['posting_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_import_staging_mapping_status'), ['mapping_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_import_staging_foreign_id'), ['foreign_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_import_staging_batch_id'), ['batch_id'], unique=False)

    with op.batch_alter_table('import_entity_mappings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_import_entity_mappings_batch_id'))
        batch_op.create_index(batch_op.f('ix_import_mapping_batch_id'), ['batch_id'], unique=False)

    with op.batch_alter_table('counts', schema=None) as batch_op:
        batch_op.drop_constraint('fk_imported_batch', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_counts_imported_from_batch_id'))
        batch_op.drop_column('imported_from_batch_id')

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tasks_store_id'))
        batch_op.drop_index(batch_op.f('ix_tasks_status'))
        batch_op.drop_index(batch_op.f('ix_tasks_org_id'))
        batch_op.drop_index(batch_op.f('ix_tasks_assigned_to_user_id'))
        batch_op.drop_index(batch_op.f('ix_tasks_assigned_to_register_id'))

    op.drop_table('tasks')
    with op.batch_alter_table('reminders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reminders_store_id'))
        batch_op.drop_index(batch_op.f('ix_reminders_org_id'))
        batch_op.drop_index(batch_op.f('ix_reminders_is_active'))

    op.drop_table('reminders')
    with op.batch_alter_table('promotions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_promotions_store_id'))
        batch_op.drop_index(batch_op.f('ix_promotions_org_id'))
        batch_op.drop_index(batch_op.f('ix_promotions_is_active'))

    op.drop_table('promotions')
    with op.batch_alter_table('organization_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_organization_settings_org_id'))

    op.drop_table('organization_settings')
    with op.batch_alter_table('device_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_device_settings_device_id'))

    op.drop_table('device_settings')
    with op.batch_alter_table('announcements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_announcements_store_id'))
        batch_op.drop_index(batch_op.f('ix_announcements_org_id'))
        batch_op.drop_index(batch_op.f('ix_announcements_is_active'))

    op.drop_table('announcements')
    # ### end Alembic commands ###
