# Overview: Alembic migration for 11 enhanced inventory operations.

"""Enhanced inventory operations - inventory states, transfers, counts

Revision ID: abc9abff25a0
Revises: e1426ef98adf
Create Date: 2026-01-15 17:19:10.521953

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'abc9abff25a0'
down_revision = 'e1426ef98adf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('counts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('document_number', sa.String(length=64), nullable=False),
    sa.Column('count_type', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('total_variance_units', sa.Integer(), nullable=True),
    sa.Column('total_variance_cost_cents', sa.Integer(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('approved_by_user_id', sa.Integer(), nullable=True),
    sa.Column('posted_by_user_id', sa.Integer(), nullable=True),
    sa.Column('cancelled_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancellation_reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['cancelled_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['posted_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_number'),
    sqlite_autoincrement=True
    )
    with op.batch_alter_table('counts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_counts_count_type'), ['count_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_counts_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_counts_store_id'), ['store_id'], unique=False)

    op.create_table('transfers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from_store_id', sa.Integer(), nullable=False),
    sa.Column('to_store_id', sa.Integer(), nullable=False),
    sa.Column('document_number', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('approved_by_user_id', sa.Integer(), nullable=True),
    sa.Column('shipped_by_user_id', sa.Integer(), nullable=True),
    sa.Column('received_by_user_id', sa.Integer(), nullable=True),
    sa.Column('cancelled_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('shipped_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancellation_reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['cancelled_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['from_store_id'], ['stores.id'], ),
    sa.ForeignKeyConstraint(['received_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['shipped_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['to_store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_number'),
    sqlite_autoincrement=True
    )
    with op.batch_alter_table('transfers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transfers_from_store_id'), ['from_store_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transfers_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_transfers_to_store_id'), ['to_store_id'], unique=False)

    op.create_table('count_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('count_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('expected_quantity', sa.Integer(), nullable=False),
    sa.Column('actual_quantity', sa.Integer(), nullable=False),
    sa.Column('variance_quantity', sa.Integer(), nullable=False),
    sa.Column('unit_cost_cents', sa.Integer(), nullable=True),
    sa.Column('variance_cost_cents', sa.Integer(), nullable=True),
    sa.Column('inventory_transaction_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['count_id'], ['counts.id'], ),
    sa.ForeignKeyConstraint(['inventory_transaction_id'], ['inventory_transactions.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sqlite_autoincrement=True
    )
    with op.batch_alter_table('count_lines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_count_lines_count_id'), ['count_id'], unique=False)

    op.create_table('transfer_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transfer_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('out_transaction_id', sa.Integer(), nullable=True),
    sa.Column('in_transaction_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['in_transaction_id'], ['inventory_transactions.id'], ),
    sa.ForeignKeyConstraint(['out_transaction_id'], ['inventory_transactions.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['transfer_id'], ['transfers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sqlite_autoincrement=True
    )
    with op.batch_alter_table('transfer_lines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transfer_lines_transfer_id'), ['transfer_id'], unique=False)

    with op.batch_alter_table('inventory_transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('inventory_state', sa.String(length=16), nullable=False))
        batch_op.create_index(batch_op.f('ix_inventory_transactions_inventory_state'), ['inventory_state'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory_transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inventory_transactions_inventory_state'))
        batch_op.drop_column('inventory_state')

    with op.batch_alter_table('transfer_lines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transfer_lines_transfer_id'))

    op.drop_table('transfer_lines')
    with op.batch_alter_table('count_lines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_count_lines_count_id'))

    op.drop_table('count_lines')
    with op.batch_alter_table('transfers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transfers_to_store_id'))
        batch_op.drop_index(batch_op.f('ix_transfers_status'))
        batch_op.drop_index(batch_op.f('ix_transfers_from_store_id'))

    op.drop_table('transfers')
    with op.batch_alter_table('counts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_counts_store_id'))
        batch_op.drop_index(batch_op.f('ix_counts_status'))
        batch_op.drop_index(batch_op.f('ix_counts_count_type'))

    op.drop_table('counts')
    # ### end Alembic commands ###
