"""phase4 sale fields

Revision ID: f80fcded54db
Revises: 
Create Date: 2026-01-13 12:40:49.542655

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f80fcded54db'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory_transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sale_id', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('sale_line_id', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('unit_cost_cents_at_sale', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('cogs_cents', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_inventory_transactions_sale_id'), ['sale_id'], unique=False)
        batch_op.create_unique_constraint('uq_invtx_store_sale_line', ['store_id', 'sale_id', 'sale_line_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory_transactions', schema=None) as batch_op:
        batch_op.drop_constraint('uq_invtx_store_sale_line', type_='unique')
        batch_op.drop_index(batch_op.f('ix_inventory_transactions_sale_id'))
        batch_op.drop_column('cogs_cents')
        batch_op.drop_column('unit_cost_cents_at_sale')
        batch_op.drop_column('sale_line_id')
        batch_op.drop_column('sale_id')

    # ### end Alembic commands ###
